<h1>Aprendendo a mexer com Numpy</h1>

In [1]:
import numpy as np

<p><h3>Trabalhando com Array</h3><p/>
    
Criando um lista para transformar em Array de uma dimensão. Para isso sera usado o metodo .array

In [2]:
minha_lista = [1, 2, 3]; minha_lista

[1, 2, 3]

In [3]:
np.array(minha_lista)

array([1, 2, 3])

Criando um lista para transformar em Array de duas dimensão

In [4]:
minha_lista = [[1, 2, 3], [7, 8, 9], [10, 11, 12]]

In [5]:
np.array(minha_lista)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

Craindo array de maneira mais simples, usando o metodo Arange.
np.arange(INICIO, FIM, PASO). Assim como em Matlab, existe alguns array's como nomes especiais, que serao vistos.

* **np.zeros(DIMENSAO1, DIMENSAO2**
* **np.ones(DIMENSAO1, DIMENSAO2)**
* **np.eye(DIMENSAO)**
* **np.linespace(INICIO, FIM, \*)**

OBS: Representa a quantidade de numeros entre INICIO e FIM igualmente espacados

In [6]:
type(np.arange(0, 10))

numpy.ndarray

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 4)

array([0, 4, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [15]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

<h3>Trabalhando com Números Aleatorios</h3>

Para criação de números aleatorios seremosa a Classe **.random.**
Dentro dessa Classe temos o método **.random.rand** que gera número(s) com um distribuição uniforme entre 0 e 1.

In [16]:
np.random.rand(5)

array([0.1571851 , 0.85626239, 0.99876483, 0.10691848, 0.16185214])

In [17]:
type(np.random.rand(5))

numpy.ndarray

Podemos gerar array tambem

In [18]:
np.random.rand(5,2)

array([[0.54860177, 0.53138276],
       [0.07797359, 0.22462175],
       [0.21288059, 0.58731807],
       [0.1704679 , 0.37695524],
       [0.89271165, 0.07492119]])

Utilizando metodo **.random.randn** que gera numeros com aleatorios com distribuição normal padrão e **.random.normal(loc = 0, scale = 1, size = None)** retorna um número aletorio com distribuição norma com media = loc , desvio = scale e size = tamanho.

In [19]:
np.random.randn(4)

array([-1.17011864, -1.11548593, -0.29610916,  0.65633484])

In [20]:
np.random.normal(0, 1, 10)

array([-0.0923176 ,  1.58384613,  0.14866962, -0.57613045,  1.1209905 ,
       -0.74457194,  0.26301867,  0.72272565, -0.42401446, -1.19797703])

Utilizando metodo **.random.randint** que gera número inteiros em um intervalo.

In [21]:
np.random.randint(0, 100, 10)

array([ 6, 62, 45, 71, 88, 82, 98, 88, 81, 32])

Trabalhando com alguns atributos no Numpy.

In [22]:
array = np.random.rand(25)

In [23]:
array

array([0.37719176, 0.45231193, 0.47323147, 0.54055732, 0.53671677,
       0.90735512, 0.96413211, 0.63585301, 0.38394781, 0.8682921 ,
       0.78772458, 0.41458984, 0.8749393 , 0.72085818, 0.10138082,
       0.91459231, 0.92909659, 0.57876187, 0.84572315, 0.68893947,
       0.2829628 , 0.43511844, 0.99558394, 0.0944187 , 0.88968024])

In [24]:
type(array)

numpy.ndarray

In [25]:
dir(array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

<h3>Alguns Atributos</h3>
<p>Usando o reshape.</p>
Ele 'remolda' seu array/matriz , podendo transformar por exemplo um matriz 1x5 em uma 5x5.
Vale resaltar que ele não substitui o array criado anteriormente.

In [26]:
array.reshape((5,5))

array([[0.37719176, 0.45231193, 0.47323147, 0.54055732, 0.53671677],
       [0.90735512, 0.96413211, 0.63585301, 0.38394781, 0.8682921 ],
       [0.78772458, 0.41458984, 0.8749393 , 0.72085818, 0.10138082],
       [0.91459231, 0.92909659, 0.57876187, 0.84572315, 0.68893947],
       [0.2829628 , 0.43511844, 0.99558394, 0.0944187 , 0.88968024]])

In [27]:
array2 = array.reshape((5,5))

Vendo as dimensões

In [28]:
array2.shape

(5, 5)

In [29]:
array.shape

(25,)

Método .max, .min e .argmax que retorna a posição do maior elementos

In [30]:
array.max()

0.9955839406462125

In [31]:
array2.max()

0.9955839406462125

In [32]:
array.min()

0.09441870287766152

In [33]:
array.argmax()

22

In [34]:
array.mean()

0.6277583853174553

In [35]:
array2.trace()

3.951666555409398

In [36]:
array.sum()

15.693959632936384

In [37]:
array.var()

0.06923870757217818

<h2>Acessando Valores num Array</h2>

In [38]:
import numpy as np

In [39]:
array = np.arange(0, 30, 3)

In [40]:
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Podemos acessar esses valores de forma parecida com um lista

In [41]:
array[3]

9

Podemos aceesar multiplos elementos, de forma parecida com o Matlab

In [42]:
array[0:6]

array([ 0,  3,  6,  9, 12, 15])

In [43]:
array[:5]

array([ 0,  3,  6,  9, 12])

In [44]:
array[1:]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

Mudando valores num Array

In [45]:
array[2:] = 10

Trabalhando com Array Bidimensionais

In [46]:
array

array([ 0,  3, 10, 10, 10, 10, 10, 10, 10, 10])

In [47]:
array2 = np.arange(0,50).reshape(5,10)

In [48]:
array2.shape

(5, 10)

Usando array[LINHA][COLUNA]  para acessar valores.

In [49]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
array2[1][2]

12

In [51]:
array2[:2][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [52]:
array2[2][0:3]

array([20, 21, 22])

In [53]:
array3 = array2[:3]

In [54]:
array3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [55]:
array3[:] = 100

In [56]:
array3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [57]:
array2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

Note que com array temos os mesmos problemas de copia que as as lista apresentam, ou seja, temos que tomar cuidado com o método usado para copia (Shallow Copy e Deep Copy)

In [58]:
array2 = np.arange(0,50).reshape(5,10)
array3 = array2.copy()

In [59]:
array3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [60]:
array3[:] = 100

In [61]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
array3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

Usando array[LINHA, COLUNA] para acessar valores. Essa forma parecida é com o Matlab

In [63]:
array2 = np.arange(0,50).reshape(5,10)

In [64]:
array2[1,2]

12

In [65]:
array2[1:3,2:4]

array([[12, 13],
       [22, 23]])

In [66]:
array2[1:3,2:]

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29]])

Acessando valores usando Boolean

In [67]:
bol = array2 >9

In [68]:
array2[bol]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [69]:
array2[bol].shape

(40,)

In [70]:
array2[bol].reshape(2, 20)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49]])

Utilizar Filter para filtar valores num array não é um alternativa muito viavel, como é mostrado a seguir.

In [71]:
array2 = np.arange(0,50).reshape(5,10)

In [72]:
array_novo = filter(lambda x: x > 9, array2)

In [73]:
array_novo

<h2>Operações com Array<h2>

In [74]:
import numpy as np

In [75]:
array1 = np.arange(0, 16)
array2 = np.arange(30, 46)

Operações entre Array

In [76]:
array1 + array2

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [77]:
array1 - array2

array([-30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30,
       -30, -30, -30])

In [78]:
array1 * array2

array([  0,  31,  64,  99, 136, 175, 216, 259, 304, 351, 400, 451, 504,
       559, 616, 675])

In [79]:
array1 / array2

array([0.        , 0.03225806, 0.0625    , 0.09090909, 0.11764706,
       0.14285714, 0.16666667, 0.18918919, 0.21052632, 0.23076923,
       0.25      , 0.26829268, 0.28571429, 0.30232558, 0.31818182,
       0.33333333])

In [80]:
array2 / array1

/Users/gabrielmizuno/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 31.        , 16.        , 11.        ,  8.5       ,
        7.        ,  6.        ,  5.28571429,  4.75      ,  4.33333333,
        4.        ,  3.72727273,  3.5       ,  3.30769231,  3.14285714,
        3.        ])

Note que a 'primeira divisão' é 30/0 o que não existe na Matematica, mas o Numpy retonar inf e um Warning.

In [81]:
array1 / array1

/Users/gabrielmizuno/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

Note que a 'primeira divisão' é 0/0 o que não existe na Matematica, mas o Numpy retonar nan e um Warning.

Operações com escalar

In [82]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [83]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [84]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [85]:
array1 ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [86]:
np.sqrt(array1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [87]:
np.exp(array1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

Lembrando que exp é o número de Neper

In [88]:
np.sin(array1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [89]:
np.arange(0, 16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Para mais informações acessar: https://docs.scipy.org/doc/numpy/reference/ufuncs.html