<h1>Aprendendo a mexer com Numpy</h1>

In [1]:
import numpy as np

<p><h3>Trabalhando com Array</h3><p/>
    
Criando um lista para transformar em Array de uma dimensão. Para isso sera usado o metodo .array

In [2]:
minha_lista = [1, 2, 3]; minha_lista

[1, 2, 3]

In [3]:
print(f'{np.array(minha_lista)}')
print(f'{np.array(minha_lista).shape}')

[1 2 3]
(3,)


In [4]:
minha_lista = [1, 2, 3]
print(f'{np.array([minha_lista])}')
print(f'{np.array([minha_lista]).shape}')

[[1 2 3]]
(1, 3)


Na primeira estou criando uma matrix uma matrix(array) 1D e na segunda 2D.

Uma matrix 1D representa como se fosse uma lista, já uma matrix 2D representa uma matrix como tabela. Portanto, em uma 1D talvez tenhamos alguns problemas de operacoes com matrizes, com por exemplo transpor, ja em uma 2D nao teremos esse problema.

In [5]:
minha_lista = [1, 2, 3]
lista = np.array(minha_lista)
matrix = np.array([minha_lista])
print(type(lista), type(matrix))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


Criando um lista para transformar em Array de duas dimensão

In [6]:
minha_lista = [[1, 2, 3], [7, 8, 9], [10, 11, 12]]

In [7]:
np.array(minha_lista)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
np.array(minha_lista).T
print(f'Matrix \n{np.array(minha_lista)}')
print(f'dimensao {np.array(minha_lista).shape}')
print(f'\nMatrix tranposta\n{np.array(minha_lista).T}')
print(f'dimensao {np.array(minha_lista).T.shape}')

Matrix 
[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]
dimensao (3, 3)

Matrix tranposta
[[ 1  7 10]
 [ 2  8 11]
 [ 3  9 12]]
dimensao (3, 3)


In [9]:
a=np.array([5,4])[0]
print(a)
# print(a.T.shape)

5


In [10]:
matrix = np.array([1, 2, 3])
matrix2 = matrix.T
matrix2.shape
matrix.shape

(3,)

Craindo array de maneira mais simples, usando o metodo Arange.
np.arange(INICIO, FIM, PASO). Assim como em Matlab, existe alguns array's como nomes especiais, que serao vistos.

* **np.zeros(DIMENSAO1, DIMENSAO2**
* **np.ones(DIMENSAO1, DIMENSAO2)**
* **np.eye(DIMENSAO)**
* **np.linespace(INICIO, FIM, \*)**

OBS: Representa a quantidade de numeros entre INICIO e FIM igualmente espacados

In [11]:
type(np.arange(0, 10))

numpy.ndarray

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 4)

array([0, 4, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [20]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

<h3>Trabalhando com Números Aleatorios</h3>

Para criação de números aleatorios seremosa a Classe **.random.**
Dentro dessa Classe temos o método **.random.rand** que gera número(s) com um distribuição uniforme entre 0 e 1.

In [21]:
np.random.rand(5)

array([0.92356661, 0.56106319, 0.19084192, 0.73420908, 0.48841543])

In [22]:
type(np.random.rand(5))

numpy.ndarray

Podemos gerar array tambem

In [23]:
np.random.rand(5,2)

array([[0.35819977, 0.64783264],
       [0.0522646 , 0.49066571],
       [0.45663799, 0.05044342],
       [0.79019915, 0.00693281],
       [0.05957165, 0.98824505]])

Utilizando metodo **.random.randn** que gera numeros com aleatorios com distribuição normal padrão e **.random.normal(loc = 0, scale = 1, size = None)** retorna um número aletorio com distribuição norma com media = loc , desvio = scale e size = tamanho.

In [24]:
np.random.randn(4)

array([-0.55029824, -0.57317806, -0.5779667 , -0.68188037])

In [25]:
np.random.normal(0, 1, 10)

array([-2.09528463,  0.01144   ,  1.7743385 , -0.58223808,  0.91435085,
       -2.4608126 , -0.72208619, -0.20220916,  0.74775051,  2.34134553])

Utilizando metodo **.random.randint** que gera número inteiros em um intervalo.

In [26]:
np.random.randint(0, 100, 10)

array([51, 63, 57, 50, 78, 18,  8, 54, 43, 76])

Trabalhando com alguns atributos no Numpy.

In [27]:
array = np.random.rand(25)

In [28]:
array

array([0.4157117 , 0.61935214, 0.16175343, 0.2418174 , 0.70766911,
       0.43373158, 0.85868619, 0.76043442, 0.36743306, 0.43223904,
       0.95619429, 0.82150728, 0.93127777, 0.51139591, 0.49216216,
       0.4862938 , 0.06732873, 0.6690977 , 0.44267912, 0.33082369,
       0.60735444, 0.01161544, 0.0339343 , 0.31852321, 0.29989914])

In [29]:
type(array)

numpy.ndarray

In [30]:
dir(array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

<h3>Alguns Atributos</h3>
<p>Usando o reshape.</p>
Ele 'remolda' seu array/matriz , podendo transformar por exemplo um matriz 1x5 em uma 5x5.
Vale resaltar que ele não substitui o array criado anteriormente.

In [31]:
array.reshape((5,5))

array([[0.4157117 , 0.61935214, 0.16175343, 0.2418174 , 0.70766911],
       [0.43373158, 0.85868619, 0.76043442, 0.36743306, 0.43223904],
       [0.95619429, 0.82150728, 0.93127777, 0.51139591, 0.49216216],
       [0.4862938 , 0.06732873, 0.6690977 , 0.44267912, 0.33082369],
       [0.60735444, 0.01161544, 0.0339343 , 0.31852321, 0.29989914]])

In [32]:
array2 = array.reshape((5,5))

Vendo as dimensões

In [33]:
array2.shape

(5, 5)

In [34]:
array.shape

(25,)

Método .max, .min e .argmax que retorna a posição do maior elementos

In [35]:
array.max()

0.956194294734598

In [36]:
array2.max()

0.956194294734598

In [37]:
array.min()

0.011615435616373015

In [38]:
array.argmax()

10

In [39]:
array.mean()

0.47915660146415945

In [40]:
array2.trace()

2.9482539220295116

In [41]:
array.sum()

11.978915036603986

In [42]:
array.var()

0.06974092513955377

<h2>Acessando Valores num Array</h2>

In [43]:
import numpy as np

In [44]:
array = np.arange(0, 30, 3)

In [45]:
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Podemos acessar esses valores de forma parecida com um lista

In [46]:
array[3]

9

Podemos aceesar multiplos elementos, de forma parecida com o Matlab

In [47]:
array[0:6]

array([ 0,  3,  6,  9, 12, 15])

In [48]:
array[:5]

array([ 0,  3,  6,  9, 12])

In [49]:
array[1:]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

Mudando valores num Array

In [50]:
array[2:] = 10

Trabalhando com Array Bidimensionais

In [51]:
array

array([ 0,  3, 10, 10, 10, 10, 10, 10, 10, 10])

In [52]:
array2 = np.arange(0,50).reshape(5,10)

In [53]:
array2.shape

(5, 10)

Usando array[LINHA][COLUNA]  para acessar valores.

In [54]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
array2[1][2]

12

In [56]:
array2[:2][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [57]:
array2[2][0:3]

array([20, 21, 22])

In [58]:
array3 = array2[:3]

In [59]:
array3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
array3[:] = 100

In [61]:
array3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [62]:
array2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

Note que com array temos os mesmos problemas de copia que as as lista apresentam, ou seja, temos que tomar cuidado com o método usado para copia (Shallow Copy e Deep Copy)

In [63]:
array2 = np.arange(0,50).reshape(5,10)
array3 = array2.copy()

In [64]:
array3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [65]:
array3[:] = 100

In [66]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
array3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

Usando array[LINHA, COLUNA] para acessar valores. Essa forma parecida é com o Matlab

In [68]:
array2 = np.arange(0,50).reshape(5,10)

In [69]:
array2[1,2]

12

In [70]:
array2[1:3,2:4]

array([[12, 13],
       [22, 23]])

In [71]:
array2[1:3,2:]

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29]])

Acessando valores usando Boolean

In [72]:
bol = array2 >9

In [73]:
array2[bol]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [74]:
array2[bol].shape

(40,)

In [75]:
array2[bol].reshape(2, 20)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49]])

Utilizar Filter para filtar valores num array não é um alternativa muito viavel, como é mostrado a seguir.

In [76]:
array2 = np.arange(0,50).reshape(5,10)

In [77]:
array_novo = filter(lambda x: x > 9, array2)

In [78]:
array_novo

<h2>Operações com Array</h2>
    
Usando vetores

In [79]:
import numpy as np

In [80]:
array1 = np.arange(0, 16)
array2 = np.arange(30, 46)

Operações entre Array

In [81]:
array1 + array2

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [82]:
array1 - array2

array([-30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30,
       -30, -30, -30])

In [83]:
array1 * array2

array([  0,  31,  64,  99, 136, 175, 216, 259, 304, 351, 400, 451, 504,
       559, 616, 675])

In [84]:
array1 / array2

array([0.        , 0.03225806, 0.0625    , 0.09090909, 0.11764706,
       0.14285714, 0.16666667, 0.18918919, 0.21052632, 0.23076923,
       0.25      , 0.26829268, 0.28571429, 0.30232558, 0.31818182,
       0.33333333])

In [85]:
array2 / array1

<ipython-input-85-a2eb6c5d0548>:1: RuntimeWarning: divide by zero encountered in true_divide
  array2 / array1


array([        inf, 31.        , 16.        , 11.        ,  8.5       ,
        7.        ,  6.        ,  5.28571429,  4.75      ,  4.33333333,
        4.        ,  3.72727273,  3.5       ,  3.30769231,  3.14285714,
        3.        ])

Note que a 'primeira divisão' é 30/0 o que não existe na Matematica, mas o Numpy retonar inf e um Warning.

In [86]:
array1 / array1

<ipython-input-86-a0b94e3cbefb>:1: RuntimeWarning: invalid value encountered in true_divide
  array1 / array1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

Note que a 'primeira divisão' é 0/0 o que não existe na Matematica, mas o Numpy retonar nan e um Warning.

Operações com escalar

In [87]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [88]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [89]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [90]:
array1 ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [106]:
np.inner(array1, array2)

4840

In [91]:
np.sqrt(array1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [92]:
np.exp(array1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

Lembrando que exp é o número de Neper

In [93]:
np.sin(array1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [94]:
np.arange(0, 16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Usando matrizes

In [95]:
matrix1 = np.array([[1, 2, 3], [7, 8, 9], [10, 11, 12]])
matrix2 = np.array([[10, 20, 30], [70, 80, 90], [100, 110, 120]])

In [96]:
np.dot(matrix1, matrix2) 

array([[ 450,  510,  570],
       [1530, 1770, 2010],
       [2070, 2400, 2730]])

In [97]:
matrix1*2

array([[ 2,  4,  6],
       [14, 16, 18],
       [20, 22, 24]])

In [98]:
matrix1**2

array([[  1,   4,   9],
       [ 49,  64,  81],
       [100, 121, 144]])

In [102]:
funcao = lambda x: 5*x + 2
print(funcao(matrix1))
funcao = lambda x: 5*np.exp(x) + 2
print(funcao(matrix1))

[[ 7 12 17]
 [37 42 47]
 [52 57 62]]
[[1.55914091e+01 3.89452805e+01 1.02427685e+02]
 [5.48516579e+03 1.49067899e+04 4.05174196e+04]
 [1.10134329e+05 2.99372709e+05 8.13775957e+05]]


In [113]:
import math
def funcao(x):
    return 5*np.exp(x) + 2

np.vectorize(funcao)(matrix1)

array([[1.55914091e+01, 3.89452805e+01, 1.02427685e+02],
       [5.48516579e+03, 1.49067899e+04, 4.05174196e+04],
       [1.10134329e+05, 2.99372709e+05, 8.13775957e+05]])

Usar funcao 'buil-in' do numpy é mais rapido do que usar numpy.vectorize

In [ ]:
np.diagonal(matrix1)

Aplicando uma funcao numa matrix por linha

In [112]:
[x.mean() for x in matrix1]

[2.0, 8.0, 11.0]

In [117]:
[5*sum(x) + 2 for x in matrix1]

[32, 122, 167]

In [118]:
funcao = lambda x: 5*sum(x) + 2
[funcao(x) for x in matrix1]

[32, 122, 167]

Aplicando uma funcao numa matrix por coluna

In [121]:
matrix1.T

array([[ 1,  7, 10],
       [ 2,  8, 11],
       [ 3,  9, 12]])

In [122]:
[x.mean() for x in matrix1.T]

[6.0, 7.0, 8.0]

In [123]:
np.mean(matrix1, axis = 1)

array([ 2.,  8., 11.])

In [124]:
np.mean(matrix1, axis = 0)

array([6., 7., 8.])

Para mais informações acessar: https://docs.scipy.org/doc/numpy/reference/ufuncs.html