<h1>Aprendendo a mexer com Numpy</h1>

In [3]:
import numpy as np

<p><h3>Trabalhando com Array</h3><p/>
    
Criando um lista para transformar em Array de uma dimensão. Para isso sera usado o metodo .array

In [6]:
minha_lista = [1, 2, 3]; minha_lista

[1, 2, 3]

In [7]:
np.array(minha_lista)

array([1, 2, 3])

Criando um lista para transformar em Array de duas dimensão

In [10]:
minha_lista = [[1, 2, 3], [7, 8, 9], [10, 11, 12]]

In [11]:
np.array(minha_lista)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

Craindo array de maneira mais simples, usando o metodo Arange.
np.arange(INICIO, FIM, PASO). Assim como em Matlab, existe alguns array's como nomes especiais, que serao vistos.
<ul>
  <li>np.zeros(DIMENSAO1, DIMENSAO2</li>
  <li>np.ones(DIMENSAO1, DIMENSAO2)</li>
  <li>np.eye(DIMENSAO)</li>
  <li>np.linespace(INICIO, FIM, *)</li>
</ul>
* Representa a quantidade de numeros entre INICIO e FIM igualmente espacados

In [28]:
type(np.arange(0, 10))

numpy.ndarray

In [29]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 4)

array([0, 4, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [23]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

<p><h3>Trabalhando com Números Aleatorios</h3><p/>
<p>Para criação de números aleatorios seremosa a Classe .random.</p>
Dentro dessa Classe temos o método rand() que gera número(s) com um distribuição uniforme entre 0 e 1.

In [5]:
np.random.rand(5)

array([0.49969919, 0.03329092, 0.93532498, 0.41844249, 0.75865279])

In [26]:
type(np.random.rand(5))

numpy.ndarray

Podemos gerar array tambem

In [30]:
np.random.rand(5,2)

array([[0.0140106 , 0.46877326],
       [0.85067532, 0.58877473],
       [0.04358803, 0.6854149 ],
       [0.38228864, 0.86609285],
       [0.90606121, 0.96301487]])

Utilizando metodo .randn que gera numeros com aleatorios com distribuição normal padrão.

In [35]:
np.random.randn(4)

array([-1.45918652, -1.01752985, -2.36224638, -0.027817  ])

Utilizando metodo .randint que gera número inteiros em um intervalo

In [36]:
np.random.randint(0, 100, 10)

array([81, 20, 69, 62, 85,  6, 28, 44,  5, 74])

Trabalhando com alguns atributos no Numpy.

In [10]:
array = np.random.rand(25)

In [43]:
array

array([7.88595707e-02, 3.46628800e-01, 2.12957933e-01, 3.70189513e-01,
       3.84332902e-01, 1.85873651e-01, 5.09280675e-01, 7.13692417e-01,
       8.93219617e-01, 3.82412660e-03, 5.93885716e-01, 8.77375699e-01,
       4.22529969e-01, 8.58156013e-01, 8.67935549e-02, 7.44049369e-01,
       6.36278367e-01, 6.47274522e-01, 7.08937927e-01, 8.34676642e-01,
       8.81463791e-02, 2.99621608e-01, 5.67286913e-01, 8.21490917e-04,
       6.85615475e-01])

In [40]:
type(array)

numpy.ndarray

In [41]:
dir(array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

<h3>Alguns Atributos</h3>
<p>Usando o reshape.</p>
Ele 'remolda' seu array/matriz , podendo transformar por exemplo um matriz 1x5 em uma 5x5.
Vale resaltar que ele não substitui o array criado anteriormente.

In [53]:
array.reshape((5,5))

array([[7.88595707e-02, 3.46628800e-01, 2.12957933e-01, 3.70189513e-01,
        3.84332902e-01],
       [1.85873651e-01, 5.09280675e-01, 7.13692417e-01, 8.93219617e-01,
        3.82412660e-03],
       [5.93885716e-01, 8.77375699e-01, 4.22529969e-01, 8.58156013e-01,
        8.67935549e-02],
       [7.44049369e-01, 6.36278367e-01, 6.47274522e-01, 7.08937927e-01,
        8.34676642e-01],
       [8.81463791e-02, 2.99621608e-01, 5.67286913e-01, 8.21490917e-04,
        6.85615475e-01]])

In [14]:
array2 = array.reshape((5,5))

Vendo as dimensões

In [45]:
array2.shape

(5, 5)

In [46]:
array.shape

(25,)

Método .max, .min e .argmax que retorna a posição do maior elementos

In [49]:
array.max()

0.8932196173447312

In [50]:
array2.max()

0.8932196173447312

In [51]:
array.min()

0.0008214909166061046

In [54]:
array.argmax()

8

In [12]:
array.mean()

0.5108501088729243

In [15]:
array2.trace()

3.0132441604062237

In [16]:
array.sum()

12.771252721823107

In [17]:
array.var()

0.0856298284082983