<h1>Aprendendo a mexer com Numpy</h1>

In [1]:
import numpy as np

<p><h3>Trabalhando com Array</h3><p/>
    
Criando um lista para transformar em Array de uma dimensão. Para isso sera usado o metodo .array

In [2]:
minha_lista = [1, 2, 3]; minha_lista

[1, 2, 3]

In [3]:
print(f'{np.array(minha_lista)}')
print(f'{np.array(minha_lista).shape}')

[1 2 3]
(3,)


In [4]:
minha_lista = [1, 2, 3]
print(f'{np.array([minha_lista])}')
print(f'{np.array([minha_lista]).shape}')

[[1 2 3]]
(1, 3)


Na primeira estou criando uma matrix uma matrix(array) 1D e na segunda 2D.

Uma matrix 1D representa como se fosse uma lista, já uma matrix 2D representa uma matrix como tabela. Portanto, em uma 1D talvez tenhamos alguns problemas de operacoes com matrizes, com por exemplo transpor, ja em uma 2D nao teremos esse problema.

In [5]:
minha_lista = [1, 2, 3]
matrix1 = np.array(minha_lista)
matrix2 = np.array([minha_lista])
print(type(matrix1), type(matrix2))
print(f'Dimensão da matrix1:{matrix1.shape}')
print(f'Dimensão da matrix2:{matrix2.shape}')

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
Dimensão da matrix1:(3,)
Dimensão da matrix2:(1, 3)


Criando um lista para transformar em Array de duas dimensão

In [6]:
minha_lista = [[1, 2, 3], [7, 8, 9], [10, 11, 12]]

In [7]:
np.array(minha_lista)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
np.array(minha_lista).T
print(f'Matrix:\n{np.array(minha_lista)}')
print(f'\ndimensao:{np.array(minha_lista).shape}')
print(f'\nMatrix tranposta:\n{np.array(minha_lista).T}')
print(f'\ndimensao:{np.array(minha_lista).T.shape}')

Matrix:
[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]

dimensao:(3, 3)

Matrix tranposta:
[[ 1  7 10]
 [ 2  8 11]
 [ 3  9 12]]

dimensao:(3, 3)


In [9]:
a=np.array([5,4])[0]
print(a)
# print(a.T.shape)

5


In [10]:
matrix = np.array([1, 2, 3])
matrix2 = matrix.T
matrix2.shape
matrix.shape

(3,)

Craindo array de maneira mais simples, usando o metodo Arange.
np.arange(INICIO, FIM, PASO). Assim como em Matlab, existe alguns array's como nomes especiais, que serao vistos.

* **np.zeros(DIMENSAO1, DIMENSAO2**
* **np.ones(DIMENSAO1, DIMENSAO2)**
* **np.eye(DIMENSAO)**
* **np.linespace(INICIO, FIM, \*)**

OBS: Representa a quantidade de numeros entre INICIO e FIM igualmente espacados

In [11]:
type(np.arange(0, 10))

numpy.ndarray

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 4)

array([0, 4, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [20]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

<h3>Trabalhando com Números Aleatorios</h3>

Para criação de números aleatorios seremosa a Classe **.random.**
Dentro dessa Classe temos o método **.random.rand** que gera número(s) com um distribuição uniforme entre 0 e 1.

In [21]:
np.random.rand(5)

array([0.92423879, 0.87810487, 0.79999363, 0.69857287, 0.76559586])

In [22]:
type(np.random.rand(5))

numpy.ndarray

Podemos gerar array tambem

In [23]:
np.random.rand(5,2)

array([[0.86156672, 0.13313783],
       [0.80680823, 0.88637675],
       [0.21627978, 0.02728965],
       [0.66106644, 0.0350001 ],
       [0.48412517, 0.08871987]])

Utilizando metodo **.random.randn** que gera numeros com aleatorios com distribuição normal padrão e **.random.normal(loc = 0, scale = 1, size = None)** retorna um número aletorio com distribuição norma com media = loc , desvio = scale e size = tamanho.

In [24]:
np.random.randn(4)

array([-2.74283925, -0.67735319,  0.162617  ,  0.30487234])

In [25]:
np.random.normal(0, 1, 10)

array([-0.6314672 ,  1.76946911, -0.77537075,  1.48990523, -2.06589705,
        0.60336442,  0.59794285,  1.6325652 ,  0.18248204, -0.83800931])

Utilizando metodo **.random.randint** que gera número inteiros em um intervalo.

In [26]:
np.random.randint(0, 100, 10)

array([86, 60,  6, 71, 55, 55, 63, 22, 28, 91])

Trabalhando com alguns atributos no Numpy.

In [27]:
array = np.random.rand(25)

In [28]:
array

array([0.21291048, 0.78471035, 0.12071997, 0.79196474, 0.95936064,
       0.16492423, 0.62613362, 0.94077297, 0.75914267, 0.93044431,
       0.07441014, 0.61067974, 0.48039618, 0.82516094, 0.26443607,
       0.73775509, 0.18463591, 0.80493076, 0.30070547, 0.29073084,
       0.97542037, 0.57969294, 0.45396947, 0.88352488, 0.46470696])

In [29]:
type(array)

numpy.ndarray

<h2>Acessando Valores num Array</h2>

In [30]:
import numpy as np

In [31]:
array = np.arange(0, 30, 3)

In [32]:
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Podemos acessar esses valores de forma parecida com um lista

In [33]:
array[3]

9

Podemos aceesar multiplos elementos, de forma parecida com o Matlab

In [34]:
array[0:6]

array([ 0,  3,  6,  9, 12, 15])

In [35]:
array[:5]

array([ 0,  3,  6,  9, 12])

In [36]:
array[1:]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

Mudando valores num Array

In [37]:
array[2:] = 10

Trabalhando com Array Bidimensionais

In [38]:
array

array([ 0,  3, 10, 10, 10, 10, 10, 10, 10, 10])

In [39]:
array2 = np.arange(0,50).reshape(5,10)

In [40]:
array2.shape

(5, 10)

<b>Usando array[LINHA][COLUNA]  para acessar valores.</b>

In [41]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
array2[1][2]

12

In [43]:
array2[:2][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [44]:
array2[2][0:3]

array([20, 21, 22])

In [45]:
array3 = array2[:3]

In [46]:
array3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [47]:
array3[:] = 100

In [48]:
array3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [49]:
array2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

Note que com array temos os mesmos problemas de copia que as as lista apresentam, ou seja, temos que tomar cuidado com o método usado para copia (Shallow Copy e Deep Copy)

In [50]:
array2 = np.arange(0,50).reshape(5,10)
array3 = array2.copy()

In [51]:
array3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
array3[:] = 100

In [53]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
array3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

Usando array[LINHA, COLUNA] para acessar valores. Essa forma parecida é com o Matlab

In [55]:
array2 = np.arange(0,50).reshape(5,10)

In [56]:
array2[1,2]

12

In [57]:
array2[1:3,2:4]

array([[12, 13],
       [22, 23]])

In [58]:
array2[1:3,2:]

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29]])

Acessando valores usando Boolean

In [59]:
bol = array2 >9

In [60]:
array2[bol]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [61]:
array2[bol].shape

(40,)

In [62]:
array2[bol].reshape(2, 20)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49]])

Utilizar Filter para filtar valores num array não é um alternativa muito viavel, pois temos que usar um list para vizualizar os dados e isto gera um erro.

In [63]:
array2 = np.arange(0,50).reshape(5,10)

In [64]:
array_novo = filter(lambda x: x > 9, array2)