<h2>Operações com Array</h2>

In [1]:
import numpy as np
import math

<h3>Operações com vetores</h3>

In [2]:
array1 = np.arange(0, 16)
array2 = np.arange(30, 46)

In [3]:
print(f'Soma:\n{array1 + array2}\n')
print(f'\nDiferença:\n{array1 - array2}\n')
print(f'\nMultiplicação entrada por entrada\n{array1 * array2}\n')
print(f'\nDivisão entrada por entrada:\n{array1 / array2}\n')
print(f'\nDivisão entrada por entrada:\n{array2 / array1}\n')
print(f'\nDivisão entrada por entrada:\n{array1 / array1}\n')

Soma:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


Diferença:
[-30 -30 -30 -30 -30 -30 -30 -30 -30 -30 -30 -30 -30 -30 -30 -30]


Multiplicação entrada por entrada
[  0  31  64  99 136 175 216 259 304 351 400 451 504 559 616 675]


Divisão entrada por entrada:
[0.         0.03225806 0.0625     0.09090909 0.11764706 0.14285714
 0.16666667 0.18918919 0.21052632 0.23076923 0.25       0.26829268
 0.28571429 0.30232558 0.31818182 0.33333333]


Divisão entrada por entrada:
[        inf 31.         16.         11.          8.5         7.
  6.          5.28571429  4.75        4.33333333  4.          3.72727273
  3.5         3.30769231  3.14285714  3.        ]


Divisão entrada por entrada:
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]



/Users/gabrielperez/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """
/Users/gabrielperez/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


Note que a 'primeira divisão' é 0/0 o que não existe na Matematica, mas o Numpy retonar nan e um Warning.


Note que a 'primeira divisão' é 0/0 o que não existe na Matematica, mas o Numpy retonar nan e um Warning.

In [4]:
print(f'\nVetor:\n{array1}\n')
print(f'\nSomando 2 em cada entrada:\n{array1 + 2}\n')
print(f'\nMultiplicando por 2 cada entrada:\n{array1 * 2}\n')
print(f'\nDividindo por 2 cada entrada:\n{array1 / 2}\n')
print(f'\nElevando por 2 cada entrada:\n{array1 ** 2}\n')
print(f'\nProduto interno:\n{np.inner(array1, array2)}\n')
print(f'\nTirando raiz em cada entrada:\n{np.sqrt(array1)}\n')
print(f'\nProduto interno:\n{np.exp(array1)}\n')
print(f'\nTirando raiz em cada entrada:\n{np.sin(array1)}\n')
print(f'\nProduto interno:\n{np.inner(array1, array2)}\n')
print(f'\nTirando raiz em cada entrada:\n{np.sqrt(array1)}\n')


Vetor:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Somando 2 em cada entrada:
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


Multiplicando por 2 cada entrada:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


Dividindo por 2 cada entrada:
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


Elevando por 2 cada entrada:
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]


Produto interno:
4840


Tirando raiz em cada entrada:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335]


Produto interno:
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]


Tirando raiz em cada entrada:
[ 0.          0.84147098  0.90929743  0.14112001 -

reshape 'remolda' seu array/matriz, transformando, por exemplo, uma matriz 1x5 em uma 5x5.

In [5]:
np.arange(1, 16).reshape((5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [6]:
np.arange(1, 16).reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
funcao = lambda x: 3*x**2 + np.exp(x) + 1
funcao(array1)

array([2.00000000e+00, 6.71828183e+00, 2.03890561e+01, 4.80855369e+01,
       1.03598150e+02, 2.24413159e+02, 5.12428793e+02, 1.24463316e+03,
       3.17395799e+03, 8.34708393e+03, 2.23274658e+04, 6.02381417e+04,
       1.63187791e+05, 4.42921392e+05, 1.20319328e+06, 3.26969337e+06])

Uma outra forma de criar arrays de forma "mais rapida"

In [12]:
x = [1, 2, 3, 4, 5]
y = [math.pi, 10, 33, 42, 100]
print(f'Preenchendo por coluna:\n{np.c_[x, y]}')
print('\n\n')
print(f'Preenchendo por linha:\n{np.r_[x, y]}')

Preenchendo por coluna:
[[  1.           3.14159265]
 [  2.          10.        ]
 [  3.          33.        ]
 [  4.          42.        ]
 [  5.         100.        ]]



Preenchendo por linha:
[  1.           2.           3.           4.           5.
   3.14159265  10.          33.          42.         100.        ]


<h3>Operações com matrizes matrizes</h3>

In [ ]:
matrix1 = np.array([[1, 2, 3], [7, 8, 9], [10, 11, 12]])
matrix2 = np.array([[10, 20, 30], [70, 80, 90], [100, 110, 120]])

In [ ]:
np.dot(matrix1, matrix2) 

In [ ]:
matrix1*2

In [ ]:
matrix1**2

In [ ]:
5*matrix1 + 2 

In [ ]:
print(f'Matrix:\n{matrix1}\n')
print(f'\nMaximo:\n{matrix1.max()}\n')
print(f'\nPosição do maximo:\n{np.argwhere(matrix1.max() == matrix1)}\n')
print(f'\nMinimo:\n{matrix1.min()}\n')
print(f'\nPosição do minimo:\n{np.argwhere(matrix1.min() == matrix1)}\n')
print(f'\nSoma:\n{matrix1.sum()}\n')
print(f'\nMedia:\n{matrix1.mean()}\n')
print(f'\nVariancia:\n{matrix1.var()}\n')
print(f'\nMediana:\n{np.median(matrix1)}\n')
print(f'\nQuantil:\n{np.quantile(matrix1, .1)}\n')
print(f'\nTraço:\n{np.trace(matrix1)}\n')

<b>Poderiamos usar funções lambdas e coisas do tipo.</b>

In [ ]:
np.diagonal(matrix1)

<b>Aplicando uma função numa matrix por linha</b>

In [ ]:
[x.mean() for x in matrix1]

In [ ]:
print(f'Matrix:\n{matrix1}\n')
print(f'\nMaximo:\n{np.mean(matrix1, axis =  1)}\n')
print(f'\nPosição do maximo:\n{np.argwhere(matrix1.max() == matrix1)}\n')
print(f'\nMinimo:\n{np.max(matrix1, axis =  1)}\n')
print(f'\nPosição do minimo:\n{np.argwhere(matrix1.min() == matrix1)}\n')
print(f'\nSoma:\n{np.sum(matrix1, axis =  1)}\n')
print(f'\nMedia:\n{np.mean(matrix1, axis =  1)}\n')
print(f'\nVariancia:\n{np.var(matrix1, axis =  1)}\n')
print(f'\nMediana:\n{np.median(matrix1, axis =  1)}\n')
print(f'\nQuantil:\n{np.quantile(matrix1, .1, axis =  1)}\n')
print(f'\nTraço:\n{np.trace(matrix1)}\n')

Note que para fazer operações por linha temos que usar funções do Numpy e não os atributos 'built-in' (como foi feito no inicio deste arquivo)

In [ ]:
[5*sum(x) + 2 for x in matrix1]

In [ ]:
funcao = lambda x: 5*sum(x) + 2
[funcao(x) for x in matrix1]

<b>Aplicando uma função numa matrix por coluna</b>

In [ ]:
matrix1.T
[x.mean() for x in matrix1.T]

In [ ]:
print(f'Matrix:\n{matrix1}\n')
print(f'\nMaximo:\n{np.mean(matrix1, axis =  0)}\n')
print(f'\nPosição do maximo:\n{np.argwhere(matrix1.max() == matrix1)}\n')
print(f'\nMinimo:\n{np.max(matrix1, axis =  0)}\n')
print(f'\nPosição do minimo:\n{np.argwhere(matrix1.min() == matrix1)}\n')
print(f'\nSoma:\n{np.sum(matrix1, axis =  0)}\n')
print(f'\nMedia:\n{np.mean(matrix1, axis =  0)}\n')
print(f'\nVariancia:\n{np.var(matrix1, axis =  0)}\n')
print(f'\nMediana:\n{np.median(matrix1, axis =  0)}\n')
print(f'\nQuantil:\n{np.quantile(matrix1, .1, axis =  0)}\n')
print(f'\nTraço:\n{np.trace(matrix1)}\n')

Note que para fazer operações por coluna temos que usar funções do Numpy e não os atributos 'built-in' (como foi feito no inicio deste arquivo)